---
# ---------------------------
#   Main playbook file       |
# ---------------------------

- name: Install neovim on Linux
  hosts: localhost
  become: true
  roles:
    - nvim
  vars:
    nvim_user: "{{ lookup('env', USER) }}"
